PIMbench/Makefile.common, PIMbench/cpp-aes/aes.cpp, PIMbench/cpp-brightness/brightness.cpp, PIMbench/cpp-histogram/hist.cpp, PIMbench/cpp-triangle-count/PIM/tc.cpp, PIMbench/util.h, misc-bench/Makefile.common, tests/Makefile.common
- Do not warn for unused variables for perf build
- Use const char * for file names
- Use %llu to print unsigned long long
- C++ style string comparison
=> Clean up warnings in benchmarks

libpimeval/src/pimParamsPerf.cpp
Bit serial performance was being called even if the device was fulcrum and bank-level.
=> Performance and energy bug fix. 

libpimeval/src/pimCmd.cpp, libpimeval/src/pimCmd.h, libpimeval/src/pimResMgr.cpp, libpimeval/src/pimResMgr.h
2nd batch of code for supporting mixed data types and element padding:
- Support querying ith element location directly from a region instead of in pimCmd
- Fixed a bug in pimRotateElementsLeft. No impact on benchmarks since it is not used.
No impact on existing behavior. Can be merged before other PRs. 
Related to Issue #16.
=> Support get ith element location in a region for mixed data types.

libpimeval/src/pimPerfEnergyModels.cpp
Fix two issues introduced today:
- From PR #89, time unit of PCL delay is not converted correctly 
- From PR #87, aggregation of numCore is reverted to numRegions
=> Fix bit-serial redsum perf formula

libpimeval/Makefile, libpimeval/src/pimCmd.cpp, libpimeval/src/pimDevice.cpp, libpimeval/src/pimDevice.h, libpimeval/src/pimPerfEnergyModels.cpp, libpimeval/src/pimPerfEnergyModels.h, libpimeval/src/pimSim.cpp, libpimeval/src/pimSim.h, libpimeval/src/pimStats.cpp, libpimeval/src/pimStats.h
PR to dev-cleanup branch for early code review and incremental development.
Reorganize code of perf energy modes:
- Rename pimParamsPerf::perfEnergy to pimNS::perfEnergy
- Define pimPerfEnergyFactory
- Define pimPerfEnergyBase, pimPerfEnergyBitSerial, pimPerfEnergyFulcrum, pimPerfEnergyBankLevel
- Move perfEnergyModel from pimSim to pimDevice because of sim target dependency
- Update related code in pimSim, pimDevice, pimCmd, pimStats
Related to Discussion #143 
Warning: It's hard to diff pimPerfEnergyModels.h/cpp. There is no change on perf and energy formulas.
=> Break perf energy models into multiple classes

libpimeval/src/pimParamsDDRDram.h, libpimeval/src/pimParamsDram.h, libpimeval/src/pimParamsLPDDRDram.h, tests/test-functional/result-golden.txt
Confirmed that the result differences are due to subtle FP type conversion behavior changes from inline functions to virtual APIs. Re-goldened results.
=> Update fp precision in pimParams.

Makefile.common, libpimeval/src/pimCmd.cpp, libpimeval/src/pimCmd.h, libpimeval/src/pimDevice.cpp, libpimeval/src/pimResMgr.cpp, libpimeval/src/pimResMgr.h, libpimeval/src/pimStats.cpp, tests/test-functional/result-golden.txt, tests/test-functional/run-pre-commit-tests.sh
Major PIMeval simulator upgrade for functional simulation memory and runtime.
Key designs:
* Support two ways of storing PIM object data
- In the data holder per PIM object, as a byte array for fast functional simulation
- In the simulated PIM memory, i.e., pimCore, for detailed memory behavior simulation such as row read/write. The simulated PIM memory is only instantiated for non-functional simulation
- All the PIM memory allocation metadata in pimObjInfo and pimRegion are maintained with no change, for performance modeling and future extension
* Code organization
- In pimResMgr.h, create pimDataHolder class
- In pimResMgr.h/cpp, create APIs in pimObjInfo for accessing the data holder, syncing data between data holder and simulated memory, and supporting reference objects
- In …
=> Decouple PIM object data and simulated memory for functional simulation memory and runtime

Makefile.common, README.md, libpimeval/Makefile, libpimeval/src/libpimeval.cpp, libpimeval/src/libpimeval.h, libpimeval/src/pimCmd.cpp, libpimeval/src/pimCmd.h, libpimeval/src/pimPerfEnergyBitSerial.cpp, libpimeval/src/pimSim.cpp, tests/test-functional/result-golden.txt, tests/test-functional/test-functional-fp.h, tests/test-functional/test-functional.h
FP32 functional support completed, requesting a merge to the main.
Changes in this commit:
- Fixed the divscalar results inconsistent issue by changing -Ofast to -O3.
- Added FP32 support for all operations.
- Code cleaning up in pimCmdFunc2 (Replacing the big if-else block with a templete function).
=> FP32 functional support for all operation completed!

tests/test-functional/fuzzy_diff.py, tests/test-functional/run-pre-commit-tests.sh
For PIMeval functional testing (test-functional), instead of calling diff, add a fuzzy_diff.py Python script to diff PIMeval outputs with a small FP error tolerance. This is because there can be small FP errors across platforms with different CPU/OS/compiler. The fuzzy_diff.py is Python2 and Python3 compatible.
With the changes, we expect to see 'PASSED' when running run-pre-commit-tests.sh on known platforms, even through there can be small FP errors between result-golden.txt and result-local.txt.
=> Support fuzzy diff for PIMeval pre-commit testing to handle small FP errors

libpimeval/src/pimPerfEnergyBankLevel.cpp, libpimeval/src/pimPerfEnergyBitSerial.cpp, libpimeval/src/pimPerfEnergyFulcrum.cpp, tests/test-functional/result-golden.txt
Bug fix: Need to provide copy command enum instead of shift/rotate command enum when estimating the perf and energy of boundary data transfer.
=> Fix perf energy estimation for element shift/rotate

libpimeval/src/libpimeval.cpp, libpimeval/src/libpimeval.h, libpimeval/src/pimCmd.cpp, libpimeval/src/pimDevice.cpp, libpimeval/src/pimSim.cpp, libpimeval/src/pimSim.h, libpimeval/src/pimUtils.h, tests/test-functional/test-functional-fp.h, tests/test-functional/test-functional-int.h
**Feature**: PIMeval analysis mode, off by default experimental feature
**Purpose**: Fast performance and energy analysis, 2-10+x
**UI to enable**: Environment variable PIMEVAL\_ANALYSIS\_MODE=1 
**Impact**: Once enabled, PIMeval will skip data copying and PIM computation during simulation for fast runtime, while the performance and energy estimation results will be identically preserved.
**Limitation**: This mode works for result-independent PIM kernels. Result-dependent PIM kernel will not work because the PIM computation results are not usable. In addition, some applications need to guard some result verification code with pimIsAnalysisMode check.
=> Support PIMeval analysis mode for fast performance and energy analysis

libpimeval/src/pimParamsDDRDram.h, libpimeval/src/pimParamsLPDDRDram.h
Updated ddr dram row read and write timing parameter to match with the datasheet
=> Row read and write timing parameter bug fix

libpimeval/src/libpimeval.h
The parameter in libpimeval.cpp is already named sum, but it is currently named min in libpimeval.h
=> Rename min to sum for pimRedSum parameter

libpimeval/src/libpimeval.cpp, libpimeval/src/libpimeval.h, libpimeval/src/pimSim.cpp, libpimeval/src/pimSim.h, libpimeval/src/pimStats.cpp, libpimeval/src/pimStats.h, tests/bitsimd-perf/bitsimd-perf.cpp
Purpose: Measure CPU/PIM portion of kernel runtime for modeling refresh. CPU runtime is based on real elapsed time. PIM runtime is based on estimated runtime.
Changes:
- Add pimStartTimer and pimEndTimer APIs to mark boundary of kernels and track CPU and PIM runtime separately
- Show stats when pimEndTimer is called
=> Measure CPU/PIM portion of kernel runtime

libpimeval/src/libpimeval.cpp, libpimeval/src/libpimeval.h, libpimeval/src/pimCmd.cpp, libpimeval/src/pimCmd.h, libpimeval/src/pimPerfEnergyBitSerial.cpp, libpimeval/src/pimSim.cpp, libpimeval/src/pimSim.h, libpimeval/src/pimUtils.cpp, libpimeval/src/pimUtils.h
Main changes:
- Add a new pimConvertType API
- Define a new CONVERT_TYPE command (does not support int-fp conversion for now)
- Minor cleanup for isSigned/isUnsigned/isFP
This is part of mixed data type support and does not affect existing simulation results. Will add more testing in following check-ins.
@fasiddique Appreciate your review effort. Thanks!
=> Support pimConvertType API as part of mixed data type support.

libpimeval/src/pimCmd.cpp, libpimeval/src/pimDevice.cpp, libpimeval/src/pimDevice.h, libpimeval/src/pimParamsDram.cpp, libpimeval/src/pimParamsDram.h, libpimeval/src/pimSim.cpp, libpimeval/src/pimSim.h, libpimeval/src/pimUtils.cpp, libpimeval/src/pimUtils.h
Main changes:
- Add pimUtils::readParamsFromConfigFile
- Consolidate three copies of config file parsing code
No impact on simulation results or simulator behavior. These are safe and clean changes that can be merged directly.
@fasiddique Appreciate your review effort. Thanks!
=> Simplify multiple copies of config file parsing code in libpimeval

libpimeval/src/libpimeval.h, libpimeval/src/pimSim.cpp, tests/test-device-APIs/test-device-APIs.cpp
Main changes:
- Add simTarget field to PimDeviceProperties struct
- Update regression test
Per request from @mhgholamrezaei : 
During functional simulation, we would like to query the simulation target in application code.
No impact on existing behavior.
=> Support simulation target in device property API.

misc-bench/string-match/README.md
Updates directory structure to match actual files, fixes a couple of typos
=> String Match: Fix readme typos

libpimeval/src/libpimeval.cpp, libpimeval/src/libpimeval.h, libpimeval/src/pimCmd.cpp, libpimeval/src/pimCmd.h, libpimeval/src/pimPerfEnergyBankLevel.cpp, libpimeval/src/pimPerfEnergyBitSerial.cpp, libpimeval/src/pimPerfEnergyFulcrum.cpp, libpimeval/src/pimSim.cpp, libpimeval/src/pimSim.h, tests/test-bit-slice/Makefile, tests/test-bit-slice/test-bit-slice.cpp
Main changes:
- Add new pimBitSliceExtract and pimBitSliceInsert operations
- Update performance and energy calculation of the two operations for bit-serial, fulcrum, and bank-level PIM
- Add a test-bit-slice application to exercise bit-slice and Boolean operations
Prerequisite features:
- Associated allocation for mixed data types, H-layout data padding, and bit-width handling
- PIM_BOOL data type support
- Mixed data type operation support: bit-slice extract dest and bit-slice insert src must be PIM_BOOL
Resolves Issue #28. Thanks for review.
=> Support bit slice operations: pimBitSliceExtract and pimBitSliceInsert

Makefile.common, README.md, libpimeval/Makefile, libpimeval/src/pimCmd.cpp, libpimeval/src/pimCmd.h, libpimeval/src/pimSim.h, libpimeval/src/pimSimConfig.h, libpimeval/src/pimStats.cpp
It's more convenient to use PIMEVAL_DEBUG env variable to toggle debug messages in categories, which avoids recompilation.
This is safe to merge. No simulator behavior impact.
=> Retire -DDEBUG macro; Switch to env var based debug flags.

libpimeval/src/pimSim.cpp, tests/test-redmax/test-redmax.cpp, tests/test-redmin/test-redmin.cpp, tests/test-redsum/test-redsum.cpp
List of changes:
- Make reduction sum work for PIM_BOOL
- Update test-redsum to cover BOOL type testing, also fix a result type issue
- Update test-redmin and test-redmax
This is related to Issue #20 
Thanks for reviewing.
=> Support reduction sum of PIM_BOOL type
